name: beanstalk
version: $version
main: love.broccolai.beanstalk.Beanstalk
loader: love.broccolai.beanstalk.lib.xyz.jpenilla.gremlin.runtime.platformsupport.DefaultsPaperPluginLoader
author: broccolai
api-version: "1.21"
permissions :
    beanstalk.admin:
        description: "Admin permissions for beanstalk"
        default: "op"
    beanstalk.user:
        description: "User permissions for beanstalk"
        default: "op"
